apiVersion: v1
kind: Service
metadata:
  name: localconveyance-service
spec:
  selector:
    app: localconveyance  # Matches the label from the deployment
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed externally
      targetPort: 5004  # The port on which your container is listening
  type: LoadBalancer  # Exposes the service through a load balancer
