apiVersion: v1
kind: Service
metadata:
  name: userlogin-service
spec:
  selector:
    app: userlogin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  selector:
    app: travel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: stay-service
spec:
  selector:
    app: stay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: localconveyance-service
spec:
  selector:
    app: localconveyance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: LoadBalancer

