apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  selector:
    app: travel  # Matches the label from the deployment
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed externally
      targetPort: 5002  # The port on which your container is listening
  type: LoadBalancer  # Exposes the service through a load balancer
