apiVersion: apps/v1
kind: Deployment
metadata:
  name: userlogin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userlogin
  template:
    metadata:
      labels:
        app: userlogin
    spec:
      containers:
      - name: userlogin
        image: gcr.io/sde-major-g39-booking-app/userlogin:latest
        ports:
        - containerPort: 5001

