apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userlogin-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userlogin
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
